import CustomStructures.MyGraph as cg

my_graph = cg.MyGraph()
my_graph.add_node(1, custom_attributes={'name': 'Oradea'})
my_graph.add_node(2, custom_attributes={'name': 'Zerind'})
my_graph.add_node(3, custom_attributes={'name': 'Arad'})
my_graph.add_node(4, custom_attributes={'name': 'Timisoara'})
my_graph.add_node(5, custom_attributes={'name': 'Lugoj'})
my_graph.add_node(6, custom_attributes={'name': 'Mechadia'})
my_graph.add_node(7, custom_attributes={'name': 'Drobeta'})
my_graph.add_node(8, custom_attributes={'name': 'Sibiu'})
my_graph.add_node(9, custom_attributes={'name': 'Rimnicu Vilcea'})
my_graph.add_node(10, custom_attributes={'name': 'Craiova'})
my_graph.add_node(11, custom_attributes={'name': 'Fagaras'})
my_graph.add_node(12, custom_attributes={'name': 'Pitesti'})
my_graph.add_node(13, custom_attributes={'name': 'Bucharest'})
my_graph.add_node(14, custom_attributes={'name': 'Giurgiu'})
my_graph.add_node(15, custom_attributes={'name': 'Neamt'})
my_graph.add_node(16, custom_attributes={'name': 'Iasi'})
my_graph.add_node(17, custom_attributes={'name': 'Vasliu'})
my_graph.add_node(18, custom_attributes={'name': 'Urziceni'})
my_graph.add_node(19, custom_attributes={'name': 'Hirsova'})
my_graph.add_node(20, custom_attributes={'name': 'Eforie'})

print(my_graph.number_of_nodes())
